### PR TITLE
Increased Code Size; Extended Statefulness; Added Basics

### PR DESCRIPTION
**Pull request by seanmay**

### CODE REVIEW

**Review by ShaunEvening — COMMENTED** [review]
Looks great, Sean. How much more in depth will you dive into your lamda calculus examples during the workshop?

**Comment by seanmay** [comment]
Not much further; I wanted to show the similarities, without teaching the thing.
An exercise (/line of questioning) that I want to run involves refactoring some code that adheres to LC concepts, but that basically becomes "PS: this is called Beta Reduction, and this other thing that you just did is Eta Conversion".

**Review by ShaunEvening — APPROVED** [review]
Okay, looks good to merge. My one concern would be that without much extra information, the lamda calculus portion would just be confusing (coming from someone who doesn't know lamda calculus)

**Comment by seanmay** [comment]
Sweet; I'll be speaking to some of that extra context, and there are a couple of other code examples pending shortly; basically, I want to drive to the fact that this is all based on some really simple and long-standing rules. If they forget Lambda Calculus 5 minutes after the introduction of "hey, this looks exactly like anonymous functions with single arguments, and these rules apply" that's fine. If they choose to look it up later, then awesome.

**Pull request merged**
